// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.887
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"grid gap-6\"><div class=\"bg-white p-6 rounded-lg shadow-md\"><h2 class=\"text-2xl font-bold mb-4\">Alpine.js の状態管理とイベント処理デモ</h2><p class=\"mb-4 text-gray-600\">以下のリンクをクリックして、各Alpine.js機能を体験してください。</p><div class=\"grid grid-cols-2 md:grid-cols-3 gap-4\"><a href=\"/basic-state\" class=\"bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded text-center\">基本状態管理</a> <a href=\"/todo-app\" class=\"bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded text-center\">TODOアプリ</a> <a href=\"/event-handling\" class=\"bg-purple-500 hover:bg-purple-600 text-white px-4 py-2 rounded text-center\">イベント処理</a> <a href=\"/global-state\" class=\"bg-yellow-500 hover:bg-yellow-600 text-white px-4 py-2 rounded text-center\">グローバル状態</a> <a href=\"/htmx-integration\" class=\"bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded text-center\">HTMX統合</a> <a href=\"/advanced-patterns\" class=\"bg-indigo-500 hover:bg-indigo-600 text-white px-4 py-2 rounded text-center\">応用パターン</a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Alpine.js デモ - ホーム").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
